name: Deploy To Namecheap VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: fastapi
          key: ${{ secrets.VPS_SECRET }}
          script: |
            cd /var/www/opabackend
            git pull
            source .venv/bin/activate
            uv sync --locked
            sudo systemctl restart fastapi
